---
- name: create "{{ prod_path }}"
  file:
    path: "{{ prod_path }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
  become: true
  become_method: sudo

- name: nginx install
  apt: name=nginx state=present
  become: true
  become_method: sudo
