require("jesseward.plugins-setup")
require("jesseward.core.options")
require("jesseward.core.keymaps")
require("jesseward.core.colorscheme")
require("jesseward.plugins.nvim-tree")
require("jesseward.plugins.comment")
require("jesseward.plugins.lualine")
require("jesseward.plugins.lsp")
require("jesseward.plugins.go")
require("jesseward.plugins.nvim-dap-go")
-- :lua vim.lsp.buf.formatting() <-- autoformat lua syntax
