---
- name: screen remove
  apt: name=screen state=absent
  become: true
  become_method: sudo

- name: tmux install
  apt: name=tmux state=present
  become: true
  become_method: sudo

- name: copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: "/home/{{ user }}/.tmux.conf"
